config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index', as: :home
  resources :requests
  get '/requests/:id/change' => 'requests#change'

  get '/search' => 'requests#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  paginates_per 7

  validates :name, presence: true
  validates :email, presence: true
  validates :department, presence: true
  validates :message, presence: true

  before_validation :set_defaults

  private

  def set_defaults
    self.status = "undone"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit([:name, :email, :department, :message])
    @request = Request.new request_params
    if @request.save
      redirect_to requests_path
    else
      render :new
    end
  end

  def show
    redirect_to requests_path
  end

  def index
    @request = Request.order(status: :desc).page params[:page]
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    @request = Request.find params[:id]
    request_params = params.require(:request).permit([:name, :email, :department, :message])
    if @request.update request_params
      redirect_to requests_path
    else
      #render plain: "Req Not Created!"
      render :edit
    end
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  def change
    @request = Request.find params[:id]
    if @request.status == "undone"
      @request.update_attribute :status, "done"
    else
      @request.update_attribute :status, "undone"
    end
    redirect_to requests_path
  end

  def search
    @q = params[:q]
    # @request = (Request.where(["name ILIKE ?", "%#{@q}%"]).order("name").page + Request.where(["email ILIKE ?", "%#{@q}%"]).order("email").page + Request.where(["department ILIKE ?", "%#{@q}%"]).order("department").page + Request.where(["message ILIKE ?", "%#{@q}%"]).order("message").page)

    @request = Request.where(["name ILIKE ? OR email ILIKE ? OR department ILIKE ? or message ILIKE ?", "%#{@q}%", "%#{@q}%", "%#{@q}%", "%#{@q}%"]).order(:status, :name).page params[:page]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<h1>home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Support</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to "Home", home_path %> |
      <%= link_to "New Request", new_request_path %> |
      <%= link_to "Requests", requests_path %>
      <hr />
    </nav>
    <%= yield %>
  </body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Request</h1>

<%= form_for @request do |r| %>
  <div>
    <%= r.label :name %>
    <%= r.text_field :name %>
  </div>
  <div>
    <%= r.label :email %>
    <%= r.text_field :email %>
  </div>
  <div>
    <%= r.radio_button :department, "sales" %>
    <%= r.label :department, "Sales" %>
    <%= r.radio_button :department, "marketing" %>
    <%= r.label :department, "Marketing" %>
    <%= r.radio_button :department, "technical" %>
    <%= r.label :department, "Technical" %>
  </div>
  <div>
    <%= r.label :message %>
    <%= r.text_area :message %>
  </div>
  <%= r.submit %>
<% end %>

app/views/requests/index.html.erb
<h1>Requests</h1>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<hr/>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th></th>
    <th>Actions</th>
    <th></th>
  </tr>
<% @request.each do |r| %>
<tr>
  <th><%= r.name %></th>
  <th><%= r.email %></th>
  <th><%= r.department %></th>
  <th><%= r.message %></th>
  <th><%= link_to "Edit", edit_request_path(r.id) %></th>
  <th><%= link_to "Delete", request_path(r.id), method: :delete, data: {confirm: 'Do you want to delete this request? '} %></th>
  <th><%= link_to r.status, "/requests/#{r.id}/change" %></th>
</tr>
<% end %>
</table>
<hr>
<center><%= paginate @request %></center>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= form_for @request do |r| %>
  <div>
    <%= r.label :name %>
    <%= r.text_field :name %>
  </div>
  <div>
    <%= r.label :email %>
    <%= r.text_field :email %>
  </div>
  <div>
    <%= r.radio_button :department, "sales" %>
    <%= r.label :department, "Sales" %>
    <%= r.radio_button :department, "marketing" %>
    <%= r.label :department, "Marketing" %>
    <%= r.radio_button :department, "technical" %>
    <%= r.label :department, "Technical" %>
  </div>
  <div>
    <%= r.label :message %>
    <%= r.text_area :message %>
  </div>
  <%= r.submit %>
<% end %>

app/views/requests/results.html.erb
<h1>Results</h1>

<hr/>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
    <th>Status</th>
  </tr>
<% @request.each do |r| %>
<tr>
  <th><%= r.name %></th>
  <th><%= r.email %></th>
  <th><%= r.department %></th>
  <th><%= r.message %></th>
  <th><%= link_to "Edit", edit_request_path(r.id) %>
      <%= link_to "Delete", request_path(r.id), method: :delete, data: {confirm: 'Do you want to delete this request? '} %></th>
  <th><%= link_to r.status, "/requests/#{r.id}/change" %></th>
</tr>
<% end %>
</table>
<hr>

app/views/requests/search.html.erb
<h1>Search Results</h1>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<p>Search for "<%= @q %>"</p>
<hr/>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th></th>
    <th>Actions</th>
    <th></th>
  </tr>
<% @request.each do |r| %>
<tr>
  <th><%= r.name %></th>
  <th><%= r.email %></th>
  <th><%= r.department %></th>
  <th><%= r.message %></th>
  <th><%= link_to "Edit", edit_request_path(r.id) %></th>
  <th><%= link_to "Delete", request_path(r.id), method: :delete, data: {confirm: 'Do you want to delete this request? '} %></th>
  <th><%= link_to r.status, "/requests/#{r.id}/change" %></th>
</tr>
<% end %>
</table>
<hr>
<center><%= paginate @request %></center>